Добавление статистики
soursager/java-explore-with-me pull request #1
Opened 2024-03-31 15:25 UTC by soursager

2024-04-01 19:34 UTC, Fleaman777 requested changes

2024-04-01 19:34 UTC, Fleaman777 commented on stat-service/server/pom.xml
> +            <version>2.7.5</version>
эти явно определенные версии можно было бы вынести в parent-pom, что бы при добавлении новых модулей, в которых будут такие же зависимости, у всех версии были одинаковыми

2024-04-01 19:34 UTC, Fleaman777 commented on stat-service/server/src/main/java/ru/practicum/ewm/server/exception/ErrorResponse.java
> +    String description;
поля должны быть private

2024-04-01 19:34 UTC, Fleaman777 commented on stat-service/server/src/main/java/ru/practicum/ewm/server/exception/ErrorResponse.java
> +    }
вместо конструтора можно использовать специальную ломбок аннотацию

2024-04-01 19:34 UTC, Fleaman777 commented on stat-service/server/src/main/java/ru/practicum/ewm/server/model/Hit.java
> +@Data
Если будет время, рекомендую почитать:
https://habr.com/ru/companies/haulmont/articles/564682/
Это о том, почему @Data и JPA лучше вместе не использовать

2024-04-01 20:43 UTC, soursager commented on stat-service/server/src/main/java/ru/practicum/ewm/server/exception/ErrorResponse.java
> +    String description;
Постоянная ошибка, когда-нибудь запомню..

2024-04-01 20:43 UTC, soursager commented on stat-service/server/pom.xml
> +            <version>2.7.5</version>
Привет! У меня при смене ноутбука развалился родительский pom, около 10 зависимостей стали красными. Очень опасаюсь трогать его еще больше, я уберу версию стартера из сервиса. Перенесу в следующем этапе, если все пойдет нормально.

2024-04-01 20:44 UTC, soursager commented on stat-service/server/src/main/java/ru/practicum/ewm/server/exception/ErrorResponse.java
> +    }
Разумеется, везде использовал, а тут нет)

2024-04-01 20:47 UTC, soursager commented on stat-service/server/src/main/java/ru/practicum/ewm/server/model/Hit.java
> +@Data
В теории наоборот было больше  информации,что нужно использовать Data, но я прочту и буду пользоваться, спасибо. Но пока оставлю так,чтобы сильно не останавливаться, иначе еще разбираться с pom нужно.....Я так понимаю тут ты про геттеры и сеттеры вообщем. Я уберу в след. этапе после исправления, если не против.

2024-04-02 19:27 UTC, Fleaman777 commented on stat-service/server/src/main/java/ru/practicum/ewm/server/model/Hit.java
> +@Data
ага, в данном проекте это не критично, больше инмформация на будущее

2024-04-02 19:28 UTC, Fleaman777 approved these changes

2024-04-02 20:28 UTC, merged