Добавление основной части проекта
soursager/java-explore-with-me pull request #2
Opened 2024-04-07 13:02 UTC by soursager

2024-04-08 14:04 UTC, Fleaman777 requested changes

2024-04-08 14:04 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/category/model/Category.java
> +        private String name;
если названия параметра name совпадает с названием поля, то можно не указывать аннотацию, 
что в целом хорошо, т.к. будет меньше кода, меньше отвлекающих факторов, 
к тому же, если все таки где-то название колонки не будет совпадать с названием поля, то мы это точно не пропустим, т.к. у нас аннотация Column будет висеть только в тех местах, где это действительно необходимо

2024-04-08 14:04 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        return CategoryMapper.toCategoryDto(repository.save(category));
метод изменяет состояние БД, правильней было бы его выполнять в транзакции, 

относится ко всем аналогичным местам

2024-04-08 14:04 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +    }
хороший общий метод

2024-04-08 14:04 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        boolean exist = repository.existsById(compId);
в принципе можно не создавать переменную, а сразу в if использовать repository.existsById(compId)

2024-04-08 14:04 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/request/service/ParticipationRequestServiceImpl.java
> +        if (event.getInitiator().equals(requester)) {
когда объекты сравниваются через equals, не забывай проверять, переобпределен ли этот метод?

2024-04-08 14:04 UTC, Fleaman777 commented on main-service/src/main/resources/schema.sql
> +    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
можно было бы добавить дефолтное время создания, 
аналагично в самой энтити, только используя спец аннотацию

2024-04-08 14:04 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/event/controller/PrivateEventController.java
> +    public EventFullDto updateEventByIdAndUserId(@RequestBody @Valid UpdateEventUserRequest updateEventUserRequest,
вроде нигде не забыл, больше как информация на будущее, 
Не забывай использовать @Valid или @Validated для валидации входящих DTO на уровне контроллеров, чтобы обеспечить корректность данных.
а так же не забывай @Valid использовать внутри вложенный DTO классов

2024-04-08 14:04 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private String title;
Если поле должно быть уникальным в базе данных, используй unique = true в @Column, чтобы гарантировать уникальность на уровне схемы БД.

2024-04-08 14:04 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/category/controller/AdminCategoryController.java
> +                                      @PathVariable @Positive Long catId) {
Валидация @Positive на ID может быть излишней, поскольку ID обычно генерируются автоматически и всегда положительны.

иначе просто не найдется айтем, что будет в рамках бизнеслогики и соответствующего эксепшен хэндлера

2024-04-08 14:04 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/category/controller/PublicCategoryController.java
> +    @RequestMapping("/{catId}")
Лучше использовать @GetMapping("/{catId}") вместо комбинации @GetMapping и @RequestMapping, чтобы сделать маршрутизацию более понятной

2024-04-08 17:44 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/category/model/Category.java
> +        private String name;
Удалил во всем моделях аннотацию Column, где название колонки совпадает с названием строки.

2024-04-08 17:45 UTC, soursager commented on main-service/src/main/resources/schema.sql
> +    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
Добавил в настройку базы данных DEFAULT NOW(), а в модель аннотацию @CreationTimestamp. Насколько я вычитал, эта аннотация присваивает значение времени при создании, возможно не прав.

2024-04-08 17:46 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +        return CategoryMapper.toCategoryDto(repository.save(category));
Добавил во всех сервисах аннотации транзакций и транзакций(только чтение) В прошлом проекте была такая же ошибку, пропустил.

2024-04-08 17:50 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/category/service/CategoryServiceImpl.java
> +    }
Взял в привычку выносить однотипный код в отдельные методы и использовать.

2024-04-08 17:51 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/request/service/ParticipationRequestServiceImpl.java
> +        if (event.getInitiator().equals(requester)) {
Переопределил в сущности методы сравнения и хеш кода. Могу ли я использовать только аннотацию вместе переопределения? При обучении использовали и одно и другое.

2024-04-08 17:53 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/event/controller/PrivateEventController.java
> +    public EventFullDto updateEventByIdAndUserId(@RequestBody @Valid UpdateEventUserRequest updateEventUserRequest,
Спасибо за совет! Везде посмотрел, не забыл и валидация есть.

2024-04-08 17:54 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/compilation/model/Compilation.java
> +    private String title;
Исправил, спасибо. Но в любом случае у меня в схеме это поле обозначено как уникальное, так что ошибок не должно возникнуть.

2024-04-08 17:56 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/category/controller/AdminCategoryController.java
> +                                      @PathVariable @Positive Long catId) {
Я указал здесь эту аннотацию в целях обхода, когда пользователь ввел отрицательное число, чтобы программа не заходила в проверку, а сразу выдавала ошибку. Я пока оставлю, но если не прав, поправь и след. части уберу данную аннотацию. Спасибо!

2024-04-08 17:57 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/category/controller/PublicCategoryController.java
> +    @RequestMapping("/{catId}")
У меня получилось так, что я использовал и первый и второй вариант) В разное время получался разный код, привел все к единообразию, спасибо.

2024-04-08 18:12 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        boolean exist = repository.existsById(compId);
Не заметил данное замечание, поэтому перезаливал

2024-04-09 18:47 UTC, Fleaman777 approved these changes

2024-04-09 19:12 UTC, merged