Добавление комментариев к событиям
soursager/java-explore-with-me pull request #3
Opened 2024-04-15 18:48 UTC by soursager

2024-04-16 19:08 UTC, Fleaman777 requested changes

2024-04-16 19:08 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/comments/service/CommentServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Пользователь не найден или недоступен"));
эту логику можно было бы вынести в общий метод

2024-04-16 19:08 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/comments/service/CommentServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Событие не найдено или недоступно"));
аналагично и с этим вызовом

2024-04-16 19:08 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/comments/service/CommentServiceImpl.java
> +        if (commentState.equals(CommentState.PUBLISHED)) {
енамы хорошо сравнивать через == 
так и сравнивается быстрее, и выглядит чуть очевидней

аналогично в др местах

2024-04-16 19:08 UTC, Fleaman777 commented on main-service/src/main/java/ru/practicum/ewm/comments/service/CommentServiceImpl.java
> +        List<CommentDto> commentDtos = commentList.stream().map(CommentMapper::toDto).collect(Collectors.toList());
этот стрим так же можно вынести в отдельный метод

2024-04-16 19:08 UTC, Fleaman777 commented on main-service/src/main/resources/schema.sql
> +    created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
респект за дефолтное значение

2024-04-17 18:12 UTC, soursager commented on main-service/src/main/resources/schema.sql
> +    created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
Привет! Я запомнил твое замечание с дефолтным значением, так же добавил аннотации @CreationTimestamp и @UpdateTimestamp. Но так как использую явное now() и дефолт в базе данных, то скорее всего это излишнее. Я думаю,что необходимо использовать или базу данных или Hibernate, так логичнее.

2024-04-17 18:12 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/comments/service/CommentServiceImpl.java
> +        List<CommentDto> commentDtos = commentList.stream().map(CommentMapper::toDto).collect(Collectors.toList());
Вынес,спасибо!

2024-04-17 18:13 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/comments/service/CommentServiceImpl.java
> +        if (commentState.equals(CommentState.PUBLISHED)) {
Я помню про это, ну вот в быстром темпе пришло в голову такое сравнение)

2024-04-17 18:13 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/comments/service/CommentServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Событие не найдено или недоступно"));
Исправил

2024-04-17 18:14 UTC, soursager commented on main-service/src/main/java/ru/practicum/ewm/comments/service/CommentServiceImpl.java
> +                .orElseThrow(() -> new NotFoundException("Пользователь не найден или недоступен"));
Постоянно использовал валидации отдельными методами, видимо хотелось быстрей отправить, спасибо)

2024-04-18 13:22 UTC, Fleaman777 commented on main-service/src/main/resources/schema.sql
> +    created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
конкретно в этом случае, не криминально использовать оба подхода одновременно, 
важнее придерживаться какого-то одного во всех сущностях где это применимо)

2024-04-18 13:22 UTC, Fleaman777 approved these changes

2024-04-18 13:29 UTC, merged